api_user: root@pam
api_token_id: maktren
api_token_secret: 8baac5e9-67be-4cf9-a02c-739d9b86e1d9
api_host: s2.maktren.local
api_password: 1qaZ15795321123
version_1c: deb64_8_3_18_1616 
password_access: 1qaZ15795321
name_server: 192.168.137.101
size_disk: 20
default_disk: virtio0
name_vm : temp-test
default_volume: /dev/sda
default_partition: 2
template_name: debian-11-template 
